name: CI

on:
  push:
    paths-ignore:
      - ".github/dependabot.yml"
      - ".github/workflows/ssh1-image.yml"
      - "docker/ssh1.Dockerfile"
      - "LICENSE"
      - "README.md"
  pull_request:
    paths-ignore:
      - ".github/dependabot.yml"
      - ".github/workflows/ssh1-image.yml"
      - "docker/ssh1.Dockerfile"
      - "LICENSE"
      - "README.md"

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.17"
      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic
      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out

  integration-tests:
    name: Integration test
    runs-on: ubuntu-latest
    container:
      image: ultram4rine/go-ssh1:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start SSH server
        run: /opt/sbin/sshd -p 2222
      - name: Run example
        working-directory: ./examples/simple
        run: go run main.go
      - name: Check file created
        run: echo "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855  /root/test/file.txt" | sha256sum -c

  build:
    name: Build
    needs:
      - unit-tests
      - integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.17"
      - name: Build
        run: go build .
